#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.2.1"
COMMIT = "1e3c246bc1c4756457894713f0d72b7c3ec7e0e6"
MAJOR = 1
MINOR = 2
PATCH = 1
