"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.0.0"
COMMIT = "1fc21e61fcd91b0e5faab13b4004e2679a081a5d"
MAJOR = 1
MINOR = 0
PATCH = 0
